{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mangrove",
    "module": "support",
    "version": "3.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "support-3.3.5.aar",
          "url": "support-3.3.5.aar",
          "size": 167346,
          "sha512": "e4fd46d80e6b4474aa7281b834e82260b2a4503a572570dbdf94346651093c7b9adad0dc1f00042995801876e697463a61410bff498f5c885dd4123be7829095",
          "sha256": "d52ccbd455a9d4ed7d95a7f078af4a752c950dd6f252a4340c1c5665516ee44e",
          "sha1": "2fb2dbb5994ca530f4f70a9faa687d0c35c2e71b",
          "md5": "1db1c26fbaaa64878061dea3a1cc3717"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "support-3.3.5.aar",
          "url": "support-3.3.5.aar",
          "size": 167346,
          "sha512": "e4fd46d80e6b4474aa7281b834e82260b2a4503a572570dbdf94346651093c7b9adad0dc1f00042995801876e697463a61410bff498f5c885dd4123be7829095",
          "sha256": "d52ccbd455a9d4ed7d95a7f078af4a752c950dd6f252a4340c1c5665516ee44e",
          "sha1": "2fb2dbb5994ca530f4f70a9faa687d0c35c2e71b",
          "md5": "1db1c26fbaaa64878061dea3a1cc3717"
        }
      ]
    }
  ]
}
